### ISSUE TITLE
translate explicitly-zoned times for people in my time zone

### ISSUE THREAD

**Issue by glasser** [mathieudutour/timezone-butler#12]
**Is your feature request related to a problem? Please describe.**
If I explicitly say `Let's have a meeting at 3pm UTC` and UTC is not my time zone, it would be helpful if I and other people in my time zone got the translation. That way I can be sure I chose the right time myself!

(Plus, this also means that when talking about events from UTC logs I can use TZB as a timezone translator! Yay!)

**Describe the solution you'd like**
My understanding of the source code is that Timezone Butler translates times for everyone not in the poster's time zone. Instead, Timezone Butler should translate times for everyone not in the time zone of the mentioned time. This is equivalent for time mentions without an explicit time zone, but different if the TZ is explicit.

**Describe alternatives you've considered**
Translate times for everyone always?

**Comment by mathieudutour** [comment]
should be fixed now
