### ISSUE TITLE
Butler interprets "12:xxpm" as midnight hour, doesn't recognize 'noon' at all

### ISSUE THREAD

**Issue by dgpokl** [mathieudutour/timezone-butler#13]
**Describe the bug**
Butler interprets "12:00pm" as midnight. While some might point out that 12:00 is technically neither AM nor PM, computers treat AM as midnight and PM as noon and many people do the same.  Plus the behavior is straight-up incorrect for times including 12:01PM-12:59PM, which are not ambiguous at all but are interpreted as though they're 12:01-12:59 AM.

Interestingly you can just type `12:00` by itself and it _will_ interpret that as noon. Not sure what to type right now to get midnight.

**To Reproduce**
1. Type "12:00pm" in a New York time zone
2. User in Los Angeles sees "12:00pm is 9pm in your timezone."
and:
1. Type "12:01pm" in a New York time zone
2. User in Los Angeles sees "12:01pm is 9:01pm in your timezone."
and:
1. Type "noon" or "midnight"
2. Nothing happens

**Expected behavior**
Butler should treat 12:xx AM as the hour that comes before 01:00 AM
Butler should notice the two keywords `noon` and `midnight`.

**Comment by dteiml** [comment]
Agree! Please fix this 🙏🏾

**Comment by dteiml** [comment]
12pm = noon.

**Comment by mdunndata** [comment]
I know it's been over a year, but I just found this repo.  Would 00:00 work for midnight?  That's how it's represented in 24-hr time.

**Comment by stephen-apto** [comment]
also experienced this issue.

**Comment by mathieudutour** [comment]
should be fixed now
