### ISSUE TITLE
Slack App asks for extensive permissions

### ISSUE THREAD

**Issue by marnovo** [mathieudutour/timezone-butler#24]
**Describe the bug**

Not exactly a bug per se, but it seems permissions may be excessive for the role & features of the bot, or maybe it's just not clear enough what features available would require them. Is there reason for each one or was it more like a catch-all?

**To Reproduce**

1. Go to https://timezone-butler.now.sh/
2. Click `Add to Slack`
3. See permissions required

**Expected behavior**

Permissions required just enough to perform the expected tasks of the bot. Adjust permissions required, or at least better explain the need for unexpected ones (e.g. upload/edit/delete files).

**Screenshots**

<img width="522" alt="Screen Shot 2019-10-22 at 5 21 49 PM" src="https://user-images.githubusercontent.com/15906764/67302011-81e35b00-f4f0-11e9-8532-2866d193c586.png">
<img width="548" alt="Screen Shot 2019-10-22 at 5 21 53 PM" src="https://user-images.githubusercontent.com/15906764/67302012-81e35b00-f4f0-11e9-879f-cdf967d4904e.png">

**Additional context**

**Comment by mathieudutour** [comment]
not anymore
