### ISSUE TITLE
Does not traverse AM/PM properly when subtracting hours

### ISSUE THREAD

**Issue by bdcrandall** [mathieudutour/timezone-butler#39]
**Describe the bug**
If you are in the eastern time zone and communicating with folks in zones farther west and try 12pm (noon) or 12am (midnight) TZ Butler doesn't do the math properly.  12pm goes to 11pm instead of 11am for central folks.

**To Reproduce**
1. Say 'I’m digging TZ butler and 12pm my time is fine'
2. View TZ Butler output in Slack for person who is 1 (or more) timezones farther west.  It will tell them 12pm is 11pm their time.

**Expected behavior**
12pm should translate to 11am, 12am should translate to 11pm.

**Screenshots**
I don't have a screenshot, just what others have told me when I put times in slack.

**Additional context**
N/A

**Comment by mathieudutour** [comment]
should be fixed now
