### ISSUE TITLE
Incorrect time conversion

### ISSUE THREAD

**Issue by dominickhera** [mathieudutour/timezone-butler#49]
**Describe the bug**

User stated in message that an event was taking place at 12:30pm CST , I am currently in the PST timezone so the expected result was to see conversion to "11:30 am" but instead the butler stated that it was "11:30 PM" in my timezone...

**To Reproduce**
1. Set slack timezone on device to PST
2. Have another user set their device to CST and say "12:30pm"
3. See error

**Expected behavior**

Butler to say "12:30pm CST is 11:30am in your timezone"
**Screenshots**
![image](https://user-images.githubusercontent.com/14668575/115449852-10ad6280-a1d0-11eb-9dbb-d8b98db413cf.png)

**Comment by sawevans** [comment]
I have the same problem, even just using the trial on the DM page for @timezonebutler. when I say 12pm, it reads it as 12am.

**Comment by toasterovenly** [comment]
You, the butler thinks that the 12pm hour is the 12 am hour and vice-versa.

**Comment by mathieudutour** [comment]
should be fixed now
