### ISSUE TITLE
12:55pm +2h is not 2:55am the next day

### ISSUE THREAD

**Issue by FreedomBenjamin** [mathieudutour/timezone-butler#60]
**Describe the bug**
When I added Timezone Butler to my Slack, I DM'd it to test it. I sent "The time is currently 12:55pm". TZ Butler replied "This is what I would say to someone in a timezone +2h compared to yours:
12:55pm is 2:55am the day after in your timezone." -- this is +14 hours, not +2 hours

**To Reproduce**
1. Say 'The time is currently 12:55pm'
2. See error as described above

**Expected behavior**
TZ Butler should give the conversion as 2:55pm

**Screenshots**
https://i.imgur.com/bClhrvO.png

**Additional context**
the issue seems to be that am and pm are mixed up for times at 12:XX -- 12:20am returns 2:20pm. Times with any other hour work properly.

**Comment by mathieudutour** [comment]
should be fixed now
