### ISSUE TITLE
Converting Eastern Time from Pacific seems to jump to the next day

### ISSUE THREAD

**Issue by HHJgl** [mathieudutour/timezone-butler#71]
**Describe the bug**
Slack user reported a screenshot this morning.  He is Eastern Timezone.  I'm Pacific.

I had shared an event notice saying that our Ergonomics Training was at 11am-12pm Pacific on Thursday.

This was the message from Timezone Butler:
**11am is 2pm in your timezone.
12pm is 3AM the day after in your timezone.**

**Screenshots**
![image](https://user-images.githubusercontent.com/101590100/158229076-d8c42ee2-cd71-4eec-b77c-493d1edd3a1b.png)

**Additional context**

**Comment by youbrokesomething** [comment]
This is because EDT is set to UTC +0 instead of UTC -4 in timezones.ts. EST is set properly and should be working as expected.

**Comment by sophieher** [comment]
Can I update fix EDT? 
Is there some other standard for EDT that it's supposed to be at 0?
Is this project still viable?

**Comment by mathieudutour** [comment]
Should be fine now
