### ISSUE TITLE
Incorrectly calculating AM/PM for times at 12:00 am/pm

### ISSUE THREAD

**Issue by aegodbold** [mathieudutour/timezone-butler#85]
**Describe the bug**

**To Reproduce**
1. When someone in EST says "1:30am" 
2. Time Butler sends a CST person the following message: "1:30am is 12:30pm the day before in your timezone."
3. When someone in EST says "1:30pm"
4. Time Butler sends a CST person the following message: 1:30pm is 12:30am in your timezone."

**Expected behavior**
When someone in EST says "1:30am", Time Buttler should say "1:30am is 12:30am in your timezone." to the CST person.
When someone in EST says "1:30am", Time Buttler should say "1:30pm is 12:30pm in your timezone." to the CST person.

**Screenshots**
The person who wrote the original message is in EST. The person who viewed the Time Butler app message is in CST.
![Screenshot 2023-01-20 122843](https://user-images.githubusercontent.com/5302096/213778162-dca977aa-45df-4bd6-a9b7-77103f8bf041.png)

**Additional context**

**Comment by mathieudutour** [comment]
Are you sure? `10:30am` is `midnight + 30 min`. So `1:30am` is indeed `12:30am + 1h`

**Comment by mathieudutour** [comment]
should be fixed now
