### ISSUE TITLE
Timezone Butler no longer posting times after Tuesday June 25

### ISSUE THREAD

**Issue by rct0110** [mathieudutour/timezone-butler#96]
Description
Timezone Butler is no longer posting time zone conversions after Tuesday June 25

**To Reproduce**
All members in the channel are able to reproduce the error:
![image](https://github.com/mathieudutour/timezone-butler/assets/166429570/10cf4123-2b9b-4d1f-8aaa-6ff33780961b)
- 

**Expected behavior**
When Timezone bot has been added to our Workspace and our channel - any times posted should have an auto reply from timezone butler clarifying your time zone
![image](https://github.com/mathieudutour/timezone-butler/assets/166429570/4329f137-1493-4572-9f8c-f446d7838218)

**Screenshots**
![image](https://github.com/mathieudutour/timezone-butler/assets/166429570/34542735-f750-4f89-88c8-23c8451c21e3)

**Comment by mathieudutour** [comment]
Yeah I received an email from slack saying that they stopped sending events:

```
Something’s not working with Timezone Butler, so we’ve temporarily stopped sending events to it
```

Haven't had time to look into it yet

**Comment by zachmian** [comment]
@mathieudutour It seems to be caused by a lack of `authed_users` in the Slack event payload, which results in an exception here https://github.com/mathieudutour/timezone-butler/blob/f8c43c6fb2e59f7639848befad2075e2a1af2476/bot/handle-slack-event.ts#L166

I think that Slack has removed this field as a part of some changes in their API (https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users)

**Comment by mathieudutour** [comment]
Interesting, I really don't remember how it was used 😅 
Do you want to open a PR to fix it?

**Comment by zachmian** [comment]
@mathieudutour sure, if possible. I've already prepared a fix and will test it in our company environment – then I can open a PR.

**Comment by mathieudutour** [comment]
I resubmitted the app for review

**Comment by dhruv-anand-aintech** [comment]
was this resolved? there's #98 and I'm also not able to get it to work

**Comment by rct0110** [comment]
@dhruv-anand-aintech  no this issue was not resolved for us.

**Comment by ywwg** [comment]
so.... basically this app is broken

**Comment by mathieudutour** [comment]
Yeah Slack killed it and wants me to do a security pen testing and a bunch of stuff which I can't be bothered with. Feel free to host it yourself and it should work fine as long as you don't try to publish it on the slack store

**Comment by ywwg** [comment]
deleting my petulant comment.  Thanks for the work and sorry they nuked it
